const styles = {
  innerWidth: "2lg:max-w-[1440px] w-full",
  interWidth: "lg:w-[80%] w-[100%]",
  paddings: "sm:py-4 py-4 lg:py-6 kiosk:py-8 sm:px-4 px-4 lg:px-6 kiosk:px-12",
  yPaddings: "sm:py-4 py-4 lg:py-6 kiosk:py-12",
  xPaddings: "sm:px-4 px-4 lg:px-6 kiosk:px-12",
  topPaddings: "sm:pt-12 xs:pt-4 pt-12",
  bottomPaddings: "sm:pb-12 xs:pb-4 pb-12",
  flexCenter: "flex justify-center items-center",
  flexCenterStart: "flex justify-center items-start",
  flexBetweenStart: "flex justify-between items-start",
  flexBetween: "flex justify-between items-center",
  flexBetweenEnd: "flex justify-between items-end",
  flexStart: "flex justify-start items-start",
  flexEnd: "flex justify-end",
  flexEndCenter: "flex justify-end items-center",
  navPadding: "pt-[98px]",
  heroHeading: "text-4xl md:text-6xl lg:text-7xl",
  H1: "text-2xl md:text-3xl lg:text-4xl",
  H2: "text-xl md:text-2xl lg:text-3xl",
  large: "text-base md:text-lg lg:text-xl",
  normal: "text-sm md:text-base",
  small: "text-[0.775rem] md:text-sm",
  Xsmall: "text-[0.7rem] md:text-[0.8rem]",
  XXsmall: "text-[0.5rem] md:text-[0.6rem]",
} as const;

export default styles;
